/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimersRouteImport } from './routes/timers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanBuilderRouteImport } from './routes/plan-builder'
import { Route as ImportGenericRouteImport } from './routes/import-generic'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DictionaryRouteImport } from './routes/dictionary'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AthleteReportRouteImport } from './routes/athlete-report'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SocialIndexRouteImport } from './routes/social.index'
import { Route as SocialSettingsRouteImport } from './routes/social.settings'
import { Route as SocialNotificationsRouteImport } from './routes/social.notifications'
import { Route as SocialDiscoverRouteImport } from './routes/social.discover'
import { Route as SocialBoardRouteImport } from './routes/social.board'
import { Route as DictionaryMovementIdRouteImport } from './routes/dictionary.$movementId'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as SocialUUsernameRouteImport } from './routes/social.u.$username'
import { Route as SocialHashtagTagRouteImport } from './routes/social.hashtag.$tag'
import { Route as ApiCronRemindersRouteImport } from './routes/api.cron.reminders'
import { Route as WorkoutMonthWeekDayRouteImport } from './routes/workout.$month.$week.$day'

const TimersRoute = TimersRouteImport.update({
  id: '/timers',
  path: '/timers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanBuilderRoute = PlanBuilderRouteImport.update({
  id: '/plan-builder',
  path: '/plan-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportGenericRoute = ImportGenericRouteImport.update({
  id: '/import-generic',
  path: '/import-generic',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryRoute = DictionaryRouteImport.update({
  id: '/dictionary',
  path: '/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AthleteReportRoute = AthleteReportRouteImport.update({
  id: '/athlete-report',
  path: '/athlete-report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialIndexRoute = SocialIndexRouteImport.update({
  id: '/social/',
  path: '/social/',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialSettingsRoute = SocialSettingsRouteImport.update({
  id: '/social/settings',
  path: '/social/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialNotificationsRoute = SocialNotificationsRouteImport.update({
  id: '/social/notifications',
  path: '/social/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialDiscoverRoute = SocialDiscoverRouteImport.update({
  id: '/social/discover',
  path: '/social/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialBoardRoute = SocialBoardRouteImport.update({
  id: '/social/board',
  path: '/social/board',
  getParentRoute: () => rootRouteImport,
} as any)
const DictionaryMovementIdRoute = DictionaryMovementIdRouteImport.update({
  id: '/$movementId',
  path: '/$movementId',
  getParentRoute: () => DictionaryRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialUUsernameRoute = SocialUUsernameRouteImport.update({
  id: '/social/u/$username',
  path: '/social/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialHashtagTagRoute = SocialHashtagTagRouteImport.update({
  id: '/social/hashtag/$tag',
  path: '/social/hashtag/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRemindersRoute = ApiCronRemindersRouteImport.update({
  id: '/api/cron/reminders',
  path: '/api/cron/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutMonthWeekDayRoute = WorkoutMonthWeekDayRouteImport.update({
  id: '/workout/$month/$week/$day',
  path: '/workout/$month/$week/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athlete-report': typeof AthleteReportRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/dictionary': typeof DictionaryRouteWithChildren
  '/health': typeof HealthRoute
  '/import': typeof ImportRoute
  '/import-generic': typeof ImportGenericRoute
  '/plan-builder': typeof PlanBuilderRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/timers': typeof TimersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/dictionary/$movementId': typeof DictionaryMovementIdRoute
  '/social/board': typeof SocialBoardRoute
  '/social/discover': typeof SocialDiscoverRoute
  '/social/notifications': typeof SocialNotificationsRoute
  '/social/settings': typeof SocialSettingsRoute
  '/social/': typeof SocialIndexRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/social/hashtag/$tag': typeof SocialHashtagTagRoute
  '/social/u/$username': typeof SocialUUsernameRoute
  '/workout/$month/$week/$day': typeof WorkoutMonthWeekDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athlete-report': typeof AthleteReportRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/dictionary': typeof DictionaryRouteWithChildren
  '/health': typeof HealthRoute
  '/import': typeof ImportRoute
  '/import-generic': typeof ImportGenericRoute
  '/plan-builder': typeof PlanBuilderRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/timers': typeof TimersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/dictionary/$movementId': typeof DictionaryMovementIdRoute
  '/social/board': typeof SocialBoardRoute
  '/social/discover': typeof SocialDiscoverRoute
  '/social/notifications': typeof SocialNotificationsRoute
  '/social/settings': typeof SocialSettingsRoute
  '/social': typeof SocialIndexRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/social/hashtag/$tag': typeof SocialHashtagTagRoute
  '/social/u/$username': typeof SocialUUsernameRoute
  '/workout/$month/$week/$day': typeof WorkoutMonthWeekDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athlete-report': typeof AthleteReportRoute
  '/calendar': typeof CalendarRoute
  '/chat': typeof ChatRoute
  '/dictionary': typeof DictionaryRouteWithChildren
  '/health': typeof HealthRoute
  '/import': typeof ImportRoute
  '/import-generic': typeof ImportGenericRoute
  '/plan-builder': typeof PlanBuilderRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/timers': typeof TimersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/dictionary/$movementId': typeof DictionaryMovementIdRoute
  '/social/board': typeof SocialBoardRoute
  '/social/discover': typeof SocialDiscoverRoute
  '/social/notifications': typeof SocialNotificationsRoute
  '/social/settings': typeof SocialSettingsRoute
  '/social/': typeof SocialIndexRoute
  '/api/cron/reminders': typeof ApiCronRemindersRoute
  '/social/hashtag/$tag': typeof SocialHashtagTagRoute
  '/social/u/$username': typeof SocialUUsernameRoute
  '/workout/$month/$week/$day': typeof WorkoutMonthWeekDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athlete-report'
    | '/calendar'
    | '/chat'
    | '/dictionary'
    | '/health'
    | '/import'
    | '/import-generic'
    | '/plan-builder'
    | '/profile'
    | '/records'
    | '/settings'
    | '/timers'
    | '/admin/videos'
    | '/dictionary/$movementId'
    | '/social/board'
    | '/social/discover'
    | '/social/notifications'
    | '/social/settings'
    | '/social/'
    | '/api/cron/reminders'
    | '/social/hashtag/$tag'
    | '/social/u/$username'
    | '/workout/$month/$week/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athlete-report'
    | '/calendar'
    | '/chat'
    | '/dictionary'
    | '/health'
    | '/import'
    | '/import-generic'
    | '/plan-builder'
    | '/profile'
    | '/records'
    | '/settings'
    | '/timers'
    | '/admin/videos'
    | '/dictionary/$movementId'
    | '/social/board'
    | '/social/discover'
    | '/social/notifications'
    | '/social/settings'
    | '/social'
    | '/api/cron/reminders'
    | '/social/hashtag/$tag'
    | '/social/u/$username'
    | '/workout/$month/$week/$day'
  id:
    | '__root__'
    | '/'
    | '/athlete-report'
    | '/calendar'
    | '/chat'
    | '/dictionary'
    | '/health'
    | '/import'
    | '/import-generic'
    | '/plan-builder'
    | '/profile'
    | '/records'
    | '/settings'
    | '/timers'
    | '/admin/videos'
    | '/dictionary/$movementId'
    | '/social/board'
    | '/social/discover'
    | '/social/notifications'
    | '/social/settings'
    | '/social/'
    | '/api/cron/reminders'
    | '/social/hashtag/$tag'
    | '/social/u/$username'
    | '/workout/$month/$week/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthleteReportRoute: typeof AthleteReportRoute
  CalendarRoute: typeof CalendarRoute
  ChatRoute: typeof ChatRoute
  DictionaryRoute: typeof DictionaryRouteWithChildren
  HealthRoute: typeof HealthRoute
  ImportRoute: typeof ImportRoute
  ImportGenericRoute: typeof ImportGenericRoute
  PlanBuilderRoute: typeof PlanBuilderRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  SettingsRoute: typeof SettingsRoute
  TimersRoute: typeof TimersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  SocialBoardRoute: typeof SocialBoardRoute
  SocialDiscoverRoute: typeof SocialDiscoverRoute
  SocialNotificationsRoute: typeof SocialNotificationsRoute
  SocialSettingsRoute: typeof SocialSettingsRoute
  SocialIndexRoute: typeof SocialIndexRoute
  ApiCronRemindersRoute: typeof ApiCronRemindersRoute
  SocialHashtagTagRoute: typeof SocialHashtagTagRoute
  SocialUUsernameRoute: typeof SocialUUsernameRoute
  WorkoutMonthWeekDayRoute: typeof WorkoutMonthWeekDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timers': {
      id: '/timers'
      path: '/timers'
      fullPath: '/timers'
      preLoaderRoute: typeof TimersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-builder': {
      id: '/plan-builder'
      path: '/plan-builder'
      fullPath: '/plan-builder'
      preLoaderRoute: typeof PlanBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-generic': {
      id: '/import-generic'
      path: '/import-generic'
      fullPath: '/import-generic'
      preLoaderRoute: typeof ImportGenericRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary': {
      id: '/dictionary'
      path: '/dictionary'
      fullPath: '/dictionary'
      preLoaderRoute: typeof DictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athlete-report': {
      id: '/athlete-report'
      path: '/athlete-report'
      fullPath: '/athlete-report'
      preLoaderRoute: typeof AthleteReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/': {
      id: '/social/'
      path: '/social'
      fullPath: '/social/'
      preLoaderRoute: typeof SocialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/settings': {
      id: '/social/settings'
      path: '/social/settings'
      fullPath: '/social/settings'
      preLoaderRoute: typeof SocialSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/notifications': {
      id: '/social/notifications'
      path: '/social/notifications'
      fullPath: '/social/notifications'
      preLoaderRoute: typeof SocialNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/discover': {
      id: '/social/discover'
      path: '/social/discover'
      fullPath: '/social/discover'
      preLoaderRoute: typeof SocialDiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/board': {
      id: '/social/board'
      path: '/social/board'
      fullPath: '/social/board'
      preLoaderRoute: typeof SocialBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictionary/$movementId': {
      id: '/dictionary/$movementId'
      path: '/$movementId'
      fullPath: '/dictionary/$movementId'
      preLoaderRoute: typeof DictionaryMovementIdRouteImport
      parentRoute: typeof DictionaryRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/u/$username': {
      id: '/social/u/$username'
      path: '/social/u/$username'
      fullPath: '/social/u/$username'
      preLoaderRoute: typeof SocialUUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social/hashtag/$tag': {
      id: '/social/hashtag/$tag'
      path: '/social/hashtag/$tag'
      fullPath: '/social/hashtag/$tag'
      preLoaderRoute: typeof SocialHashtagTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/reminders': {
      id: '/api/cron/reminders'
      path: '/api/cron/reminders'
      fullPath: '/api/cron/reminders'
      preLoaderRoute: typeof ApiCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$month/$week/$day': {
      id: '/workout/$month/$week/$day'
      path: '/workout/$month/$week/$day'
      fullPath: '/workout/$month/$week/$day'
      preLoaderRoute: typeof WorkoutMonthWeekDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DictionaryRouteChildren {
  DictionaryMovementIdRoute: typeof DictionaryMovementIdRoute
}

const DictionaryRouteChildren: DictionaryRouteChildren = {
  DictionaryMovementIdRoute: DictionaryMovementIdRoute,
}

const DictionaryRouteWithChildren = DictionaryRoute._addFileChildren(
  DictionaryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthleteReportRoute: AthleteReportRoute,
  CalendarRoute: CalendarRoute,
  ChatRoute: ChatRoute,
  DictionaryRoute: DictionaryRouteWithChildren,
  HealthRoute: HealthRoute,
  ImportRoute: ImportRoute,
  ImportGenericRoute: ImportGenericRoute,
  PlanBuilderRoute: PlanBuilderRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  SettingsRoute: SettingsRoute,
  TimersRoute: TimersRoute,
  AdminVideosRoute: AdminVideosRoute,
  SocialBoardRoute: SocialBoardRoute,
  SocialDiscoverRoute: SocialDiscoverRoute,
  SocialNotificationsRoute: SocialNotificationsRoute,
  SocialSettingsRoute: SocialSettingsRoute,
  SocialIndexRoute: SocialIndexRoute,
  ApiCronRemindersRoute: ApiCronRemindersRoute,
  SocialHashtagTagRoute: SocialHashtagTagRoute,
  SocialUUsernameRoute: SocialUUsernameRoute,
  WorkoutMonthWeekDayRoute: WorkoutMonthWeekDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
