/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutMonthWeekDayRouteImport } from './routes/workout.$month.$week.$day'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutMonthWeekDayRoute = WorkoutMonthWeekDayRouteImport.update({
  id: '/workout/$month/$week/$day',
  path: '/workout/$month/$week/$day',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/workout/$month/$week/$day': typeof WorkoutMonthWeekDayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/workout/$month/$week/$day': typeof WorkoutMonthWeekDayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/import': typeof ImportRoute
  '/settings': typeof SettingsRoute
  '/workout/$month/$week/$day': typeof WorkoutMonthWeekDayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/import'
    | '/settings'
    | '/workout/$month/$week/$day'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/import' | '/settings' | '/workout/$month/$week/$day'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/import'
    | '/settings'
    | '/workout/$month/$week/$day'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  ImportRoute: typeof ImportRoute
  SettingsRoute: typeof SettingsRoute
  WorkoutMonthWeekDayRoute: typeof WorkoutMonthWeekDayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/$month/$week/$day': {
      id: '/workout/$month/$week/$day'
      path: '/workout/$month/$week/$day'
      fullPath: '/workout/$month/$week/$day'
      preLoaderRoute: typeof WorkoutMonthWeekDayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  ImportRoute: ImportRoute,
  SettingsRoute: SettingsRoute,
  WorkoutMonthWeekDayRoute: WorkoutMonthWeekDayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
